// <auto-generated />
using System;
using MagicVilla.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MagicVilla.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Amenity")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("Rate")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = 5.0,
                            CreatedDate = new DateTime(2025, 7, 17, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Luxurious villa with ocean view.",
                            ImageUrl = "https://example.com/images/villa1.jpg",
                            Name = "Sea Breeze Villa",
                            Rate = 350.0,
                            UpdatedDate = new DateTime(2025, 7, 17, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = 4.0,
                            CreatedDate = new DateTime(2025, 7, 17, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Peaceful villa in the mountains.",
                            ImageUrl = "https://example.com/images/villa2.jpg",
                            Name = "Mountain Retreat",
                            Rate = 280.0,
                            UpdatedDate = new DateTime(2025, 7, 17, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Amenity = 4.0,
                            CreatedDate = new DateTime(2025, 7, 17, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Villa with a stunning lake view.",
                            ImageUrl = "https://example.com/images/villa3.jpg",
                            Name = "Lakeview Paradise",
                            Rate = 300.0,
                            UpdatedDate = new DateTime(2025, 7, 17, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Amenity = 3.0,
                            CreatedDate = new DateTime(2025, 7, 17, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Modern villa in the desert.",
                            ImageUrl = "https://example.com/images/villa4.jpg",
                            Name = "Desert Oasis",
                            Rate = 260.0,
                            UpdatedDate = new DateTime(2025, 7, 17, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            Amenity = 4.0,
                            CreatedDate = new DateTime(2025, 7, 17, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Remote villa in the tropical forest.",
                            ImageUrl = "https://example.com/images/villa5.jpg",
                            Name = "Jungle Hideout",
                            Rate = 240.0,
                            UpdatedDate = new DateTime(2025, 7, 17, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            Amenity = 5.0,
                            CreatedDate = new DateTime(2025, 7, 17, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Luxurious villa in the city center.",
                            ImageUrl = "https://example.com/images/villa6.jpg",
                            Name = "City Lights Villa",
                            Rate = 400.0,
                            UpdatedDate = new DateTime(2025, 7, 17, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            Amenity = 4.0,
                            CreatedDate = new DateTime(2025, 7, 17, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cozy villa in a snowy region.",
                            ImageUrl = "https://example.com/images/villa7.jpg",
                            Name = "Snowy Chalet",
                            Rate = 320.0,
                            UpdatedDate = new DateTime(2025, 7, 17, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            Amenity = 5.0,
                            CreatedDate = new DateTime(2025, 7, 17, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Villa on a private island.",
                            ImageUrl = "https://example.com/images/villa8.jpg",
                            Name = "Island Bungalow",
                            Rate = 500.0,
                            UpdatedDate = new DateTime(2025, 7, 17, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            Amenity = 3.0,
                            CreatedDate = new DateTime(2025, 7, 17, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Elegant historic villa with antique decor.",
                            ImageUrl = "https://example.com/images/villa9.jpg",
                            Name = "Historic Manor",
                            Rate = 290.0,
                            UpdatedDate = new DateTime(2025, 7, 17, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            Amenity = 5.0,
                            CreatedDate = new DateTime(2025, 7, 17, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Minimalist villa perched on a cliff.",
                            ImageUrl = "https://example.com/images/villa10.jpg",
                            Name = "Modern Cliff House",
                            Rate = 420.0,
                            UpdatedDate = new DateTime(2025, 7, 17, 12, 0, 0, 0, DateTimeKind.Utc)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
