FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

COPY ["MagicVilla/MagicVilla.csproj", "MagicVilla/"]
COPY ["MagicVilla_Utility/MagicVilla_Utility.csproj", "MagicVilla_Utility/"]
RUN dotnet restore "MagicVilla/MagicVilla.csproj"

COPY . .
WORKDIR "/src/MagicVilla"
RUN dotnet publish "MagicVilla.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS final
WORKDIR /app
COPY --from=build /app/publish .

ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080

ENTRYPOINT ["dotnet", "MagicVilla.dll"]
